### ISSUE TITLE
setup claimer test credential not working

### ISSUE THREAD

**Issue by MoMannn** [KILTprotocol/kilt-distillery-cli#5]
When trying to setup claimer test credentials trough the cli I get the following error:

```
 KILT DISTILLERY CLI - Self-attesting the claims...
2022-10-17 14:22:06        API/INIT: Not decorating unknown runtime apis: DidApi/1
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

This worked a few weeks ago.
Tried on node version 18 and 16.

**Comment by 1nfused** [comment]
Confirming issue.

**Comment by lrazovic** [comment]
I confirm the problem, tested on macOS 12.6 ARM64 with Node v18.11.0 and on Linux x86_64 with Node v16.16.0.
To reproduce the problem: 
1. `npx git+https://github.com/KILTprotocol/kilt-distillery-cli`
2. Option number 2: "setup claimer test credential"
3. After the  "KILT DISTILLERY CLI - get testnet tokens to continue" phase you first notice the error `2022-10-20 09:26:06        API/INIT: Not decorating unknown runtime apis: DidApi/1`, but CLI keeps going
4. If you continue in the process eventually the error reported by @MoMannn is returned
